# Server port
server.port=8080

# App name shown
spring.application.name=LMS Automator

# Increase max file size for large downloads passing through Spring
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Show cleaner logs
logging.level.root=INFO
logging.level.com.downloadc=DEBUG